regietool/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'regietool.views.home', name='home'),
    url(r'^stock/', include('stock.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',

	url(r'^$', 'stock.views.home'),
	url(r'^(?P<matos_id>\d+)/$', 'stock.views.detail_matos'),
	)

stock/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django import forms

class Matos(models.Model):

	CATEGORIE_CHOICES = (
		('lum', 'Lumière'),
		('son', 'Son'),
		('vid', 'Vidéo'),
		('pla', 'Plateau'),
		)

	SOUS_CATEGORIE_CHOICES = [
		("Lumière",(
			('prj', "Projecteur"),
			('pup', "Jeux d'orgue"),
			('dim', "Gradateur"),
			)),
		("Son", (
			('enc', 'Enceinte'),
			('mic', 'Microphone'),
			('amp', 'Amplificateur'),
			('mix', 'Table de mixage'),
			('prc', 'Processing'),
			)),
		("Vidéo", (
			('vip', 'Vidéo projecteur'),
			)),
		('cab', 'Câble'),
		('sup', 'Support'),
		]

	TYPE_PROJ_CHOICES = [
		('Traditionnel',(
			('pc', 'Plan convexe'),
			('fre', 'Fresnel'),
			('dec', 'Découpe'),
			('par', 'PAR'),
			('qua', 'Quartz'),
			('bat', 'Basse tension'),
			)),
		('Asservi', (
			('lyr', 'Lyre'),
			('pal', 'Par led'),
			('str', 'Stromboscope'),
			)),	
		('aut', 'Autre'),
		]

	TYPE_MICRO_CHOICES = (
		('DYN', 'Micro dynamique'),
		('CON', 'Micro à condensateur'),
		('RUB', 'Micro à ruban'),
		)

	DIRECTIVITE_CHOICES = (
		('OMN', 'Omnidirectionnel'),
		('CAR', 'Cardioïde'),
		('HYP', 'HyperCardioïde'),
		('CAN', 'Canon'),
		)
	
	nom = models.CharField('nom usuel', max_length = 50)
	image = models.ImageField(upload_to = 'img/', blank=True)
	categorie = models.CharField('catégorie',max_length=3, choices=CATEGORIE_CHOICES)
	sous_categorie = models.CharField('sous catégorie',max_length=3, choices=SOUS_CATEGORIE_CHOICES)
	q_stock = models.IntegerField('quantité', max_length=5, default=1)
	details = models.TextField('caractéristiques', blank=True)
	marque = models.CharField('marque', max_length=32, blank=True)
	model = models.CharField('modèle', max_length=32, blank=True)
	poids = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True, help_text = 'En kilogramme(s)', default = 0)
	hauteur = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, help_text = 'En mètre(s)', default = 0)
	largeur = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, help_text = 'En mètre(s)', default = 0)
	profondeur = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, help_text = 'En mètre(s)', default = 0)
	date_achat = models.DateField("date d'achat", blank=True, null=True)
	date_check = models.DateField("vérifié le ", blank=True, null=True)
	date_modif = models.DateTimeField(auto_now = True, verbose_name = 'Date de modification')
	date_ajout = models.DateTimeField(auto_now_add = True, verbose_name = "Date d'ajout")
	asbl = models.NullBooleanField('Matériel ASBL', blank=True, null=True) 

# Projecteur
	type_proj = models.CharField('type de projecteur', max_length=3, blank=True, null=True, choices=TYPE_PROJ_CHOICES)
	puissance_proj = models.IntegerField('puissance', max_length=5, blank=True, null=True, help_text='En watt(s)')
	tension_proj = models.IntegerField('tension', max_length=3, blank=True, null=True, help_text='En volt(s)')
	angle_min = models.IntegerField('angle minimum', max_length=3, blank=True, null=True, help_text='En degré(s)')
	angle_max = models.IntegerField('angle maximum', max_length=3, blank=True, null=True ,help_text='En degré(s)')
	has_dmx = models.NullBooleanField('DMX', null=True, blank=True)

# Micro
	directivite = models.CharField('directivité', max_length=3, choices= DIRECTIVITE_CHOICES, blank=True)
	sensibilite = models.DecimalField('sensibilité', max_digits=4, decimal_places=2, blank=True, null=True, help_text = 'En mV/Pa')
	type_micro = models.CharField('type de micro', max_length=21, choices= TYPE_MICRO_CHOICES, blank=True)
	freq_min = models.IntegerField(max_length=5, blank=True, null=True, help_text='En hertz')
	freq_max = models.IntegerField(max_length=5, blank=True, null=True, help_text='En hertz')
	
# Enceinte

		
# Ampli

	

	def __unicode__(self):
		return u"%s" %self.nom 

class SearchForm(forms.Form):
	CATEGORIE_CHOICES = (
		('None', '---------'),
		('lum', 'Lumière'),
		('son', 'Son'),
		('vid', 'Vidéo'),
		('pla', 'Plateau'),
		)
	SOUS_CATEGORIE_CHOICES = [
	('None', '---------'),
	("Lumière",(
		('prj', "Projecteur"),
		('pup', "Jeux d'orgue"),
		('dim', "Gradateur"),
		)),
	("Son", (
		('enc', 'Enceinte'),
		('mic', 'Microphone'),
		('amp', 'Amplificateur'),
		('mix', 'Table de mixage'),
		('prc', 'Processing'),
		)),
	("Vidéo", (
		('vip', 'Vidéo projecteur'),
		)),
	('cab', 'Câble'),
	('sup', 'Support'),
	]

	categorie = forms.ChoiceField(choices=CATEGORIE_CHOICES, label="catégorie")
	sous_categorie = forms.ChoiceField(choices=SOUS_CATEGORIE_CHOICES, label="sous catégorie")

stock/forms.py
from django import forms

stock/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404 , render_to_response
from django.template import RequestContext
from stock.models import *
import pdb

def home(request):

	list_matos = Matos.objects.all().order_by('date_modif').reverse()
	form = SearchForm()
	if request.method == 'POST':
		form = SearchForm(request.POST)
		choix_categorie = request.POST['categorie']
		choix_sous_categorie = request.POST['sous_categorie']
		if choix_categorie != 'None':
			if choix_sous_categorie != 'None':
				list_matos = Matos.objects.filter(categorie=choix_categorie).filter(sous_categorie=choix_sous_categorie).order_by('date_modif')
				pass
			else : 
				list_matos = Matos.objects.filter(categorie=choix_categorie)
				pass
		elif choix_sous_categorie != 'None':
			list_matos = Matos.objects.filter(sous_categorie=choix_sous_categorie)
			pass

		else : 
			list_matos = Matos.objects.all().order_by('categorie', 'sous_categorie')
			pass
		return render_to_response('stock/home.html', 
		{'list_matos': list_matos, 'form': form}, 
		context_instance=RequestContext(request))
	else:
		return render_to_response('stock/home.html', 
		{'list_matos': list_matos, 'form': form}, 
		context_instance=RequestContext(request))

def detail_matos(request, matos_id):
    matos = get_object_or_404(Matos, pk=int(matos_id))
    
    if matos.sous_categorie == 'prj':
    	return render_to_response('stock/matos_projecteur.html', {'matos': matos }, context_instance=RequestContext(request))
    elif matos.categorie == 'enc':
    	return render_to_response('stock/matos_enceinte.html', {'matos': matos }, context_instance=RequestContext(request))
    elif matos.categorie == 'mic':
    	return render_to_response('stock/matos_micro.html', {'matos': matos }, context_instance=RequestContext(request))
    elif matos.categorie == 'pla':
    	return render_to_response('stock/matos_plateau.html', {'matos': matos }, context_instance=RequestContext(request))
    else:
    	return render_to_response('stock/detail_matos.html', {'matos': matos }, context_instance=RequestContext(request))

stock/templates/stock/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="fr">

    <head>

        {% block head %}
            <link rel="stylesheet" href="{% static 'stock/style.css' %}" />
        {% endblock %}
    </head>
  
    <body class="ui-widget">       
        <header>
        {% block header %}

        {% endblock %}           
        </header>
        
        <nav >
        {% block nav %}
            
        {% endblock %}   
        </nav>                 
            
        <section id='section1'>
        {% block section1 %}
        {% endblock %}
        </section>
        
        <section id='section2'>
        {% block section2 %}
        {% endblock %}
        </section>
        
    </body>
</html>

stock/templates/stock/detail_matos.html
{% extends "stock/base.html" %}	
{% load staticfiles %}

{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Régie Tool !!!{% endblock %}</title>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/ui-lightness/jquery-ui.css">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'stock/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src"http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

	<script type='text/javascript'>
	$(document).ready(function(){
		$('#home-logo').click(function(){
			document.location.href='/stock/';
		})
		
	});
	</script>
{% endblock %}

{% block header %}
	{% if matos %}
		<div>
			<img id='home-logo' src="{% static 'stock/back.png' %}" alt="Home" />
		</div>
			<center id="nom-matos">{{matos.nom}}</center>
		<div>
			{% if matos.image %}
				<img id='img-matos' src="{{ matos.image.url }}" alt="{{ matos.nom }}" width="90" />
			{% endif %}
		</div>
	{% endif %}
{% endblock %}



{% block section1 %}


{% endblock %}

stock/templates/stock/home.html
{% extends "stock/base.html" %}	
{% load staticfiles %}	

{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Régie Tool !!!{% endblock %}</title>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/ui-lightness/jquery-ui.css">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'stock/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src"http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
	<script src="{% static 'stock/jquery.hideseek.min.js' %}"></script>

	<script type='text/javascript'> /* JQuery plugins */
	$(document).ready(function(){
		$('#search').hideseek({  
		});
		$( "#id_categorie" ).selectmenu({
			change: function() {
				document.forms[0].submit()}
		});
		$( "#id_sous_categorie" ).selectmenu({
			change: function() {
				document.forms[0].submit()
		}});
		$( "#selectable" ).selectable({
           	selected: function(){
           		var href = $('.ui-selected + a').attr('href');
           		document.location.href=href;
           	}
    	});			
	});
	</script>
{% endblock %}

{% block header %}
    <center id="text-accueil" class="ui-widget-header">Salut !</center>
{% endblock %}

{% block nav %}
<section>
<input id="search" name="search" placeholder="Recherche..." type="text" data-list="#selectable">

<form action="/stock/" id="select_form" method="POST">
	{% csrf_token %}
		{{ form.categorie }}
		{{ form.sous_categorie }}
</form>
</section>
{% endblock %}

{% block section1 %}
<ol id="selectable">
	{% for matos in list_matos %}
		<li class="ui-widget-content matos-item">{{matos.nom}}</li>
		<a class="items_list" href ='/stock/{{matos.id}}/'></a>
	{% endfor %}
</ol>
{% endblock %}

stock/templates/stock/matos_lumiere.html
{% extends "stock/base.html" %}	
{% load staticfiles %}

{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Régie Tool !!!{% endblock %}</title>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/ui-lightness/jquery-ui.css">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'stock/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src"http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

	<script type='text/javascript'>
	$(document).ready(function(){
		$('#home-logo').click(function(){
			document.location.href='/stock/';
		})
		
	});
	</script>
{% endblock %}

{% block header %}
	{% if matos %}
		<div>
			<img id='home-logo' src="{% static 'stock/back.png' %}" alt="Home" />
		</div>
			<center id="nom-matos">{{matos.nom}}</center>
		<div>
			{% if matos.image %}
				<img id='img-matos' src="{{ matos.image.url }}" alt="{{ matos.nom }}" width="90" />
			{% endif %}
		</div>
	{% endif %}
{% endblock %}



{% block section1 %}


{% endblock %}

stock/templates/stock/matos_projecteur.html
{% extends "stock/base.html" %}	
{% load staticfiles %}

{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Régie Tool !!!{% endblock %}</title>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/ui-lightness/jquery-ui.css">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'stock/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src"http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

	<script type='text/javascript'>
	$(document).ready(function(){
		$('#home-logo').click(function(){
			document.location.href='/stock/';
		});
		$('#accordion').accordion({

		});
		
	});
	</script>
{% endblock %}

{% block header %}
	{% if matos %}
		<div>
			<img id='home-logo' src="{% static 'stock/back.png' %}" alt="Home" />
		</div>
		<center id="nom-matos">{{matos.nom}}</center>
		
	{% endif %}
{% endblock %}

{% block section1 %}
	{% if matos %}
		
		<div id="accordion">
			
			<h3>Général</h3>
				<div>

				<ul class="fiche" id="fiche_matos">
   					<li>
    					<label for="type_proj">Type :</label>
    					<span name="marque" id="marque"/>{{matos.get_type_proj_display}}</span>
   					</li>
   					<li>
    					<label for="puissance_proj">Puissance :</label>
    					<span name="puissance_proj" id="puissance_proj"/>{{matos.puissance_proj}} watts</span>
   					</li>
   					<li>
    					<label for="marque">Marque :</label>
    					<span name="marque" id="marque"/>{{matos.marque}}</span>
   					</li>
   					<li>
    					<label for="model">Modèle :</label>
    					<span name="model" id="model"/>{{matos.model}}</span>
   					</li>
   				</ul>	
				</div>
			<h3>Détails</h3>
				<div>
					<p>
						{{matos.details|linebreaks}}
					</p>
				</div>
			<h3>Photo</h3>
				<div>
					{% if matos.image %}
						<img id='img-matos' src="{{ matos.image.url }}" alt="{{ matos.nom }}" />
					{% endif %}
				</div>
		</div>

	{% endif %}



{% endblock %}

stock/templates/stock/matos_son.html
{% extends "stock/base.html" %}	
{% load staticfiles %}

{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Régie Tool !!!{% endblock %}</title>
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/ui-lightness/jquery-ui.css">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
	<link rel="stylesheet" href="{% static 'stock/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src"http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

	<script type='text/javascript'>
	$(document).ready(function(){
		$('#home-logo').click(function(){
			document.location.href='/stock/';
		})
		
	});
	</script>
{% endblock %}

{% block header %}
	{% if matos %}
		<div>
			<img id='home-logo' src="{% static 'stock/back.png' %}" alt="Home" />
		</div>
			<center id="nom-matos">{{matos.nom}}</center>
		<div>
			{% if matos.image %}
				<img id='img-matos' src="{{ matos.image.url }}" alt="{{ matos.nom }}" width="90" />
			{% endif %}
		</div>
	{% endif %}
{% endblock %}



{% block section1 %}
<p> Son !!! </p>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

    <head>
        {% block head %}

        {% endblock %}
    </head>
  

    <body>       
        <header>
        {% block header %}
            <h3>Gestion du parc matériel</h3> 
        {% endblock %}           
        </header>
        
        <nav>
        {% block nav %}
        {% endblock %}   
        </nav>                 
            
        <section id='section1'>
        {% block section1 %}
        {% endblock %}
        </section>
        
        <section id='section2'>
        {% block section2 %}
        {% endblock %}
        </section>
        
        
            
    </body>
</html>